export type Project = {
  id:           number
  slug:         string
  title:        string
  category:     string
  year:         string
  image:        string   /* hero + listing thumbnail */
  client:       string
  typology:     string
  status:       string
  location:     string
  discipline:   string
  description:  string   /* short intro below hero */
  quote:        string   /* large pull-quote */
  aboutText:    string   /* body copy under quote */
  stickyImage:  string   /* small left sticky portrait */
  largeImage:   string   /* large right portrait */
  gallery:      string[] /* variable-length gallery */
}

export const PROJECTS: Project[] = [
  {
    id:          1,
    slug:        'belgrade-waterfront',
    title:       'Belgrade Waterfront',
    category:    'Mixed-Use',
    year:        '2022',
    image:       '/projects/belgrade-waterfront/00 DNEVNA 1a.webp',
    client:      'Private Client',
    typology:    'Mixed-Use Development',
    status:      'Completed',
    location:    'Belgrade, Serbia',
    discipline:  'Architecture & Interior',
    description: 'A landmark mixed-use development set along the Sava riverfront, combining residential, retail, and public promenade into a single cohesive urban gesture.',
    quote:       'A waterfront is not a boundary — it is the city\'s most generous threshold.',
    aboutText:   'Positioned along a key stretch of the Belgrade waterfront, this development reactivates a previously industrial edge with a layered programme of residences, ground-floor retail, and a continuous public promenade. The massing steps down toward the water, preserving view corridors from the city above while creating a new civic edge at river level. Materials respond to the industrial heritage of the site — exposed concrete, weathered steel, and textured brick — paired with warm timber in all inhabited spaces.',
    stickyImage: '/projects/belgrade-waterfront/01 DNEVNA 3.webp',
    largeImage:  '/projects/belgrade-waterfront/soba B8.webp',
    gallery: [
      '/projects/belgrade-waterfront/03 KUHINJA 2 (1).webp',
      '/projects/belgrade-waterfront/01 DNEVNA 2 a.webp',
      '/projects/belgrade-waterfront/soba A9.webp',
      '/projects/belgrade-waterfront/wc 2.webp',
    ],
  },
  {
    id:          2,
    slug:        'villa-corso',
    title:       'Villa Corso',
    category:    'Residential',
    year:        '2023',
    image:       '/projects/Villa-corso/kuh jed 2.webp',
    client:      'Private Client',
    typology:    'Residential',
    status:      'Completed',
    location:    'Italy',
    discipline:  'Architecture & Interior',
    description: 'A private villa that negotiates between the Italian landscape and a refined contemporary interior language, balancing openness and enclosure with precision.',
    quote:       'The villa as an instrument of light — each room a considered threshold between inside and out.',
    aboutText:   'Villa Corso occupies a gently sloping site in northern Italy, oriented to capture long views across the surrounding countryside. The plan organises the programme around a central courtyard that draws light deep into the house and provides a sheltered outdoor room for daily life. All interior spaces were designed in close collaboration with the client — custom joinery, curated furniture, and bespoke lighting compose an environment that feels entirely singular.',
    stickyImage: '/projects/Villa-corso/master kop 2.webp',
    largeImage:  '/projects/Villa-corso/master kop 3.webp',
    gallery: [
      '/projects/Villa-corso/dnevna 5.webp',
      '/projects/Villa-corso/master 1.webp',
      '/projects/Villa-corso/kuh jed 5.webp',
      '/projects/Villa-corso/studio 3.webp',
    ],
  },
  {
    id:          3,
    slug:        'my-skin-bar',
    title:       'My Skin Bar',
    category:    'Commercial',
    year:        '2023',
    image:       '/projects/My-Skin_bar/01.webp',
    client:      'My Skin Bar',
    typology:    'Beauty & Wellness',
    status:      'Completed',
    location:    'Italy',
    discipline:  'Interior Design',
    description: 'A boutique skincare studio designed to feel like a curated domestic space — intimate, refined, and entirely focused on the experience of care.',
    quote:       'Wellness begins with the environment — a space that calms before treatment even starts.',
    aboutText:   'This project transforms a modest street-level unit into a premium skincare destination. The brief called for an environment that communicates expertise without clinical coldness. The result is a layered interior of pale stone, brushed brass, and soft upholstery — materials that read as tactile and considered. Treatment rooms are organised along a single corridor, each one a self-contained sensory environment with controlled lighting and acoustic privacy.',
    stickyImage: '/projects/My-Skin_bar/04.webp',
    largeImage:  '/projects/My-Skin_bar/06.webp',
    gallery: [
      '/projects/My-Skin_bar/08.webp',
      '/projects/My-Skin_bar/13 injectables 1.webp',
      '/projects/My-Skin_bar/15 wc.webp',
    ],
  },
  {
    id:          4,
    slug:        'san-gwann',
    title:       'San Gwann',
    category:    'Residential',
    year:        '2022',
    image:       '/projects/San_Gwann/kuhinja 0b.webp',
    client:      'Private Client',
    typology:    'Residential',
    status:      'Completed',
    location:    'San Gwann, Malta',
    discipline:  'Architecture & Interior',
    description: 'A residential project in the heart of Malta that draws from the island\'s limestone building tradition while delivering a rigorously contemporary living environment.',
    quote:       'The Mediterranean vernacular offers no shortcuts — only a discipline that rewards patience.',
    aboutText:   'Set in the established residential neighbourhood of San Gwann, this project involved the complete redesign and extension of an existing house. The project responds to the Maltese climate through deep shaded openings, cross-ventilation, and a material palette centred on local globigerina limestone. Interiors are calm and uncluttered, with custom furniture designed to work with the proportions of each room. A new rooftop terrace captures panoramic views across the island.',
    stickyImage: '/projects/San_Gwann/soba 4.webp',
    largeImage:  '/projects/San_Gwann/kuhinja 2b.webp',
    gallery: [
      '/projects/San_Gwann/kuhinja 3b.webp',
      '/projects/San_Gwann/kuhinja 4b.webp',
    ],
  },
  {
    id:          5,
    slug:        'via-bellini',
    title:       'Via Bellini I & II',
    category:    'Residential',
    year:        '2021',
    image:       '/projects/Via-bellini_1/09.webp',
    client:      'Private Client',
    typology:    'Residential',
    status:      'Completed',
    location:    'Italy',
    discipline:  'Interior Design',
    description: 'Two residential apartments on Via Bellini, each individually redesigned — one pursuing a minimal contemporary approach, the other a warmer Mediterranean palette — both sharing the same precision of craft.',
    quote:       'Two apartments, one philosophy — precision, warmth, and materials that age with grace.',
    aboutText:   'Via Bellini presented two separate commissions within the same building — a rare opportunity to develop two distinct but related interior languages for neighbouring apartments. Apartment I pursues a stripped-back contemporary aesthetic: light stone surfaces, integrated joinery, and a restrained palette of white and natural timber. Apartment II takes a warmer direction — richer tones, textured plaster, and furniture with a stronger character. Both share the same commitment to resolved detail: every junction, every material transition, considered and precise.',
    stickyImage: '/projects/Via-bellini_1/00.webp',
    largeImage:  '/projects/Via-bellini_2/master 2b.webp',
    gallery: [
      '/projects/Via-bellini_1/03a.webp',
      '/projects/Via-bellini_2/1 dnevna 2.webp',
      '/projects/Via-bellini_1/06.webp',
      '/projects/Via-bellini_2/kupatilo 2c1.webp',
      '/projects/Via-bellini_1/10.webp',
      '/projects/Via-bellini_2/4 kuhinja 2b 2.webp',
    ],
  },
  {
    id:          6,
    slug:        'via-cappuccini',
    title:       'Via Cappuccini',
    category:    'Residential',
    year:        '2024',
    image:       '/projects/Cappucinni/3.webp',
    client:      'Private Client',
    typology:    'Residential',
    status:      'Completed',
    location:    'Italy',
    discipline:  'Architecture & Interior',
    description: 'A carefully resolved apartment renovation on one of the city\'s most storied streets — a dialogue between inherited structure and new inhabitation.',
    quote:       'Restraint is not poverty of imagination — it is the highest form of precision.',
    aboutText:   'Via Cappuccini is a residential renovation within a historic Italian building, working within strict conservation constraints to deliver a contemporary interior of genuine quality. Existing stone floors and ornate ceilings were retained and carefully restored, forming the backdrop for a new layer of bespoke joinery and curated furnishings. Every detail was resolved with the original architecture in mind — materials, junctions, and proportions all informed by what was already there.',
    stickyImage: '/projects/Cappucinni/6.webp',
    largeImage:  '/projects/Cappucinni/13a.webp',
    gallery: [
      '/projects/Cappucinni/15.webp',
      '/projects/Cappucinni/19.webp',
    ],
  },
  {
    id:          7,
    slug:        'casino-laos',
    title:       'Casino',
    category:    'Hospitality',
    year:        '2022',
    image:       '/projects/Casino/Casino_laos.webp',
    client:      'Private Client',
    typology:    'Hospitality & Entertainment',
    status:      'Completed',
    location:    'Laos',
    discipline:  'Architecture & Interior',
    description: 'A hospitality and entertainment complex in Southeast Asia — an architecture of atmosphere, crafted to create immersive environments across a range of guest experiences.',
    quote:       'An interior that commands attention from first entry — every surface, every threshold considered.',
    aboutText:   'This project in Laos presented a rare opportunity to design at scale for a hospitality programme across an entire new building. The architecture is bold in its massing and restrained in its detail — a composition of strong geometric volumes clad in local stone and timber, softened by landscape. The interiors develop a rich material language: lacquered joinery, textured plaster, custom lighting, and carefully specified furniture across gaming, dining, and lounge environments.',
    stickyImage: '/projects/Casino/Casino_laos_1.webp',
    largeImage:  '/projects/Casino/Casino_laos_2.webp',
    gallery: [
      '/projects/Casino/Casino_laos_3.webp',
      '/projects/Casino/Casino_laos_4.webp',
      '/projects/Casino/Casino_laos_5.webp',
    ],
  },
  {
    id:          8,
    slug:        'eda-center',
    title:       'Eda Center',
    category:    'Commercial',
    year:        '2021',
    image:       '/projects/Eda-center/3.webp',
    client:      'Eda Group',
    typology:    'Commercial',
    status:      'Completed',
    location:    'Slovenia',
    discipline:  'Architecture & Interior',
    description: 'A commercial centre in Slovenia conceived as a place of encounter — architecture that elevates the everyday retail and business experience through quality of space and material.',
    quote:       'Commerce can be dignified — architecture can make an ordinary errand feel considered.',
    aboutText:   'The Eda Center brings together retail, office, and service programmes within a single coherent building. The design challenges the typical commercial typology by introducing generous public atrium spaces, natural light throughout, and a material palette well above the sector norm. Façade treatments vary by orientation to manage solar gain and visual interest, while the ground floor is designed with flexibility to accommodate a range of tenants without compromising the spatial quality of shared areas.',
    stickyImage: '/projects/Eda-center/4.webp',
    largeImage:  '/projects/Eda-center/12.webp',
    gallery: [
      '/projects/Eda-center/13.webp',
      '/projects/Eda-center/Enscape_2022-12-19-15-34-57.webp',
    ],
  },
  {
    id:          9,
    slug:        'beauty-clinic',
    title:       'Beauty Clinic',
    category:    'Commercial',
    year:        '2023',
    image:       '/projects/beauty-clinic/123 Hiška - ARTISANA-02.webp',
    client:      'Private Client',
    typology:    'Medical & Wellness',
    status:      'Completed',
    location:    'Slovenia',
    discipline:  'Interior Design',
    description: 'A medical aesthetic clinic designed to convey clinical precision and genuine luxury simultaneously — a space where rigorous standards and considered hospitality coexist.',
    quote:       'Trust is built in the details — and clients feel them before they can name them.',
    aboutText:   'This beauty clinic in Slovenia required an interior that communicates the highest clinical standards while creating an experience that feels genuinely welcoming and premium. The spatial sequence moves from a warm, residential-feeling reception through increasingly private consultation and treatment zones. Materials were selected for both cleanability and visual warmth — honed stone surfaces, integrated cabinetry in soft lacquer, and carefully layered lighting that adapts to each stage of the client journey.',
    stickyImage: 'https://images.unsplash.com/photo-1560472355-536de3962603?w=800',
    largeImage:  'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200',
    gallery: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900',
    ],
  },
]
