export type Project = {
  id:           number
  slug:         string
  title:        string
  category:     string
  year:         string
  image:        string   /* hero + listing thumbnail */
  client:       string
  typology:     string
  status:       string
  location:     string
  discipline:   string
  description:  string   /* short intro below hero */
  quote:        string   /* large pull-quote */
  aboutText:    string   /* body copy under quote */
  stickyImage:  string   /* small left sticky portrait */
  largeImage:   string   /* large right portrait */
  gallery:      string[] /* variable-length gallery */
}

export const PROJECTS: Project[] = [
  {
    id:          1,
    slug:        'castagnola-lugano',
    title:       'Castagnola',
    category:    'Mixed-Use',
    year:        '2026',
    image:       '/projects/Castagnola/office_2.webp',
    client:      'Private Client',
    typology:    'Mixed-Use Development',
    status:      'Completed',
    location:    'Lugano, Switzerland',
    discipline:  'Interior',
    description: 'A refined private residence in one of Lugano’s most exclusive districts, where bespoke interiors, panoramic views, and curated materials come together in a cohesive expression of contemporary living.',
    quote:       'Luxury is not excess — it is the quiet precision of spaces made to endure.',
    aboutText:   'Located in one of Lugano’s most exclusive areas, this project interprets contemporary living with restraint and character. Bespoke furnishings in Canaletto walnut and Calacatta marble define warm and sophisticated interiors, conceived to showcase artworks and collectible objects. Wall panelling, bookcases, and integrated storage become elegant architectural backdrops, while expansive glazing amplifies natural light and panoramic views. A cohesive composition that fully reflects the client’s refined taste.',
    stickyImage: '/projects/Castagnola/bedroom_1.webp',
    largeImage:  '/projects/Castagnola/closet.webp',
    gallery: [
      '/projects/Castagnola/office_1.webp',
      '/projects/Castagnola/bedroom_4.webp',
      '/projects/Castagnola/coridor.webp',
      '/projects/Castagnola/bedroom_3.webp',
    ],
  },
  {
    id:          2,
    slug:        'villa-corso',
    title:       'Villa Corso',
    category:    'Residential',
    year:        '2023',
    image:       '/projects/Villa-corso/kuh jed 2.webp',
    client:      'Private Client',
    typology:    'Residential',
    status:      'Completed',
    location:    'Italy',
    discipline:  'Architecture & Interior',
    description: 'A private villa that negotiates between the Italian landscape and a refined contemporary interior language, balancing openness and enclosure with precision.',
    quote:       'The villa as an instrument of light — each room a considered threshold between inside and out.',
    aboutText:   'Interior design project for an early 20th-century residence, entirely reimagined for contemporary living. The concept enhances proportion, light, and spatial continuity, creating fluid and scenographic interiors. Elegant living areas, a dedicated music room, and tailored circulation paths establish a coherent design language. The master suite integrates a refined bathroom and generous dressing room, while the two children’s bedrooms — both en suite — are designed around the needs of modern family life. Premium materials and light sculpt every detail.',
    stickyImage: '/projects/Villa-corso/master kop 2.webp',
    largeImage:  '/projects/Villa-corso/master kop 3.webp',
    gallery: [
      '/projects/Villa-corso/dnevna 5.webp',
      '/projects/Villa-corso/master 1.webp',
      '/projects/Villa-corso/kuh jed 5.webp',
      '/projects/Villa-corso/studio 3.webp',
    ],
  },
  {
    id:          3,
    slug:        'my-skin-bar',
    title:       'My Skin Bar',
    category:    'Commercial',
    year:        '2023',
    image:       '/projects/My-Skin_bar/01.webp',
    client:      'My Skin Bar',
    typology:    'Beauty & Wellness',
    status:      'Completed',
    location:    'Italy',
    discipline:  'Interior Design',
    description: 'A boutique skincare studio designed to feel like a curated domestic space — intimate, refined, and entirely focused on the experience of care.',
    quote:       'Wellness begins with the environment — a space that calms before treatment even starts.',
    aboutText:   'An organic and immersive design language where architecture and identity merge into a sensory spatial experience. Warm tones inspired by skin create an intimate and protective environment, while soft, continuous geometries remove any sense of rigidity. Niches, arches, and sculpted surfaces amplify depth and light, producing an almost tactile aesthetic. The project communicates care, delicacy, and wellbeing — translating the language of beauty into space.',
    stickyImage: '/projects/My-Skin_bar/04.webp',
    largeImage:  '/projects/My-Skin_bar/06.webp',
    gallery: [
      '/projects/My-Skin_bar/08.webp',
      '/projects/My-Skin_bar/13 injectables 1.webp',
      '/projects/My-Skin_bar/15 wc.webp',
    ],
  },
  {
    id:          4,
    slug:        'san-gwann',
    title:       'San Gwann',
    category:    'Residential',
    year:        '2022',
    image:       '/projects/San_Gwann/kuhinja 0b.webp',
    client:      'Private Client',
    typology:    'Residential',
    status:      'Completed',
    location:    'San Gwann, Malta',
    discipline:  'Architecture & Interior',
    description: 'A residential project in the heart of Malta that draws from the island\'s limestone building tradition while delivering a rigorously contemporary living environment.',
    quote:       'The Mediterranean vernacular offers no shortcuts — only a discipline that rewards patience.',
    aboutText:   'In the heart of San Ġwann, this apartment emerges from the meeting of practicality and atmosphere. The kitchen disappears behind a timber wall, allowing for a fluid environment that transforms naturally: living room and music studio coexist seamlessly. Softer light within the kitchen zone is paired with warm materials and muted tones. Every element is designed to optimise space, creating an interior that is intimate, elegant, and deeply personal.',
    stickyImage: '/projects/San_Gwann/soba 4.webp',
    largeImage:  '/projects/San_Gwann/kuhinja 2b.webp',
    gallery: [
      '/projects/San_Gwann/kuhinja 3b.webp',
      '/projects/San_Gwann/kuhinja 4b.webp',
    ],
  },
  {
    id:          5,
    slug:        'via-bellini',
    title:       'Via Bellini I & II',
    category:    'Residential',
    year:        '2021',
    image:       '/projects/Via-bellini_1/09.webp',
    client:      'Private Client',
    typology:    'Residential',
    status:      'Completed',
    location:    'Italy',
    discipline:  'Interior Design',
    description: 'Two residential apartments on Via Bellini, each individually redesigned — one pursuing a minimal contemporary approach, the other a warmer Mediterranean palette — both sharing the same precision of craft.',
    quote:       'Two apartments, one philosophy — precision, warmth, and materials that age with grace.',
    aboutText:   'Within an early 20th-century Central European building, the project reinterprets Art Nouveau style through a contemporary lens. Two apartment typologies were developed: more compact ground-floor units enhanced by mezzanines, and larger apartments with layouts completely reimagined for modern living. Warm materials, brass detailing, and sophisticated tones define elegant and functional interiors where historic architecture and contemporary comfort coexist in harmonious, fluid, and character-rich spaces.',
    stickyImage: '/projects/Via-bellini_1/00.webp',
    largeImage:  '/projects/Via-bellini_2/master 2b.webp',
    gallery: [
      '/projects/Via-bellini_1/03a.webp',
      '/projects/Via-bellini_2/1 dnevna 2.webp',
      '/projects/Via-bellini_1/06.webp',
      '/projects/Via-bellini_2/kupatilo 2c1.webp',
      '/projects/Via-bellini_1/10.webp',
      '/projects/Via-bellini_2/4 kuhinja 2b 2.webp',
    ],
  },
  {
    id:          6,
    slug:        'via-cappuccini',
    title:       'Via Cappuccini',
    category:    'Residential',
    year:        '2024',
    image:       '/projects/Cappucinni/3.webp',
    client:      'Private Client',
    typology:    'Residential',
    status:      'Completed',
    location:    'Italy',
    discipline:  'Architecture & Interior',
    description: 'A carefully resolved apartment renovation on one of the city\'s most storied streets — a dialogue between inherited structure and new inhabitation.',
    quote:       'Restraint is not poverty of imagination — it is the highest form of precision.',
    aboutText:   'Set within an early 20th-century building, the project redefines ten apartments through a complete renovation that updates the layouts for contemporary living. Generous ceiling heights allowed for the introduction of a raised floor system to integrate building services. Warm materials, seamless surfaces, and bespoke detailing engage with the original character of the building, inspired by the romantic elegance of Art Nouveau style.',
    stickyImage: '/projects/Cappucinni/6.webp',
    largeImage:  '/projects/Cappucinni/13a.webp',
    gallery: [
      '/projects/Cappucinni/15.webp',
      '/projects/Cappucinni/19.webp',
    ],
  },
  {
    id:          7,
    slug:        'casino-laos',
    title:       'Casino',
    category:    'Hospitality',
    year:        '2022',
    image:       '/projects/Casino/Casino_laos.webp',
    client:      'Private Client',
    typology:    'Hospitality & Entertainment',
    status:      'Completed',
    location:    'Laos',
    discipline:  'Architecture & Interior',
    description: 'A hospitality and entertainment complex in Southeast Asia — an architecture of atmosphere, crafted to create immersive environments across a range of guest experiences.',
    quote:       'An interior that commands attention from first entry — every surface, every threshold considered.',
    aboutText:   'Keeping Eastern taste in mind — rich in gold, patterns, and symbolic references — we reinterpreted it through a European design language defined by elegant proportions and controlled lines. The project creates a contemporary vision of luxury, where luminous marble, warm timber, and metallic detailing interact with scenographic features such as the large circular bar and monumental aquarium, an iconic presence referencing the auspicious fish of Eastern tradition. Lighting, conceived as architecture, amplifies depth and atmosphere, defining a sophisticated and distinctive space.',
    stickyImage: '/projects/Casino/Casino_laos_1.webp',
    largeImage:  '/projects/Casino/Casino_laos_2.webp',
    gallery: [
      '/projects/Casino/Casino_laos_3.webp',
      '/projects/Casino/Casino_laos_4.webp',
      '/projects/Casino/Casino_laos_5.webp',
    ],
  },
  {
    id:          8,
    slug:        'eda-center',
    title:       'Eda Center',
    category:    'Commercial',
    year:        '2021',
    image:       '/projects/Eda-center/3.webp',
    client:      'Eda Group',
    typology:    'Commercial',
    status:      'Completed',
    location:    'Slovenia',
    discipline:  'Architecture & Interior',
    description: 'A commercial centre in Slovenia conceived as a place of encounter — architecture that elevates the everyday retail and business experience through quality of space and material.',
    quote:       'Commerce can be dignified — architecture can make an ordinary errand feel considered.',
    aboutText:   'For this approximately 1,000 sqm headquarters within a new-generation tower, the project interprets the corporate workplace through a sophisticated and material-led lens. Continuous glazing and structural columns become ordering elements within a fluid and efficient layout. Glass partitions amplify natural light, while timber and three-dimensional volumes improve acoustic comfort and spatial perception. Bespoke furnishings and layered lighting define an elegance that is measured, contemporary, and representative.',
    stickyImage: '/projects/Eda-center/4.webp',
    largeImage:  '/projects/Eda-center/12.webp',
    gallery: [
      '/projects/Eda-center/13.webp',
      '/projects/Eda-center/Enscape_2022-12-19-15-34-57.webp',
    ],
  },
  {
    id:          9,
    slug:        'beauty-clinic',
    title:       'Beauty Clinic',
    category:    'Commercial',
    year:        '2023',
    image:       '/projects/Beauty-clinic/ARTISANA-02.webp',
    client:      'Private Client',
    typology:    'Medical & Wellness',
    status:      'Completed',
    location:    'Slovenia',
    discipline:  'Interior Design',
    description: 'A medical aesthetic clinic designed to convey clinical precision and genuine luxury simultaneously — a space where rigorous standards and considered hospitality coexist.',
    quote:       'Trust is built in the details — and clients feel them before they can name them.',
    aboutText:   'Located in Ljubljana, this beauty clinic is conceived as an elegant and measured space, where the language of the interior reflects the precision and harmony of aesthetic medicine. Large-format continuous surfaces define the interiors, paired with warm timber and soft finishes. Artistic and chromatic accents enrich the space, while diffused and calibrated lighting enhances volumes and materials, creating an atmosphere that is welcoming, controlled, and sophisticated.',
    stickyImage: '/projects/Beauty-clinic/ARTISANA-09a.webp',
    largeImage:  '/projects/Beauty-clinic/ARTISANA-08b.webp',
    gallery: [
      '/projects/Beauty-clinic/ARTISANA-01a.webp',
      '/projects/Beauty-clinic/ARTISANA-12a.webp',
      '/projects/Beauty-clinic/ARTISANA-05a.webp',
      '/projects/Beauty-clinic/ARTISANA-13a.webp',
    ],
  },
  {
    id:          10,
    slug:        'belgrade-waterfront',
    title:       'Belgrade Waterfront',
    category:    'Mixed-Use',
    year:        '2022',
    image:       '/projects/belgrade-waterfront/00 DNEVNA 1a.webp',
    client:      'Private Client',
    typology:    'Mixed-Use Development',
    status:      'Completed',
    location:    'Belgrade, Serbia',
    discipline:  'Architecture & Interior',
    description: 'A landmark mixed-use development set along the Sava riverfront, combining residential, retail, and public promenade into a single cohesive urban gesture.',
    quote:       'A waterfront is not a boundary — it is the city\'s most generous threshold.',
    aboutText:   'Located within the new Eden Building in Belgrade Waterfront, this project expresses a refined aesthetic inspired by luxury hospitality, responding to the client’s desire to recreate the feeling of an exclusive and sophisticated environment. Walnut, leather, and velvet define a rich material palette, elevated by marble surfaces and theatrical lighting, creating an elegant and balanced atmosphere.',
    stickyImage: '/projects/belgrade-waterfront/01 DNEVNA 3.webp',
    largeImage:  '/projects/belgrade-waterfront/soba B8.webp',
    gallery: [
      '/projects/belgrade-waterfront/03 KUHINJA 2 (1).webp',
      '/projects/belgrade-waterfront/01 DNEVNA 2 a.webp',
      '/projects/belgrade-waterfront/soba A9.webp',
      '/projects/belgrade-waterfront/wc 2.webp',
    ],
  },
]
